### ISSUE TITLE
何子潇--周报

### ISSUE THREAD

**Issue by harrymtheone** [ChuangGeKeXie/2019-3-24#13]
上周：
~找出了那个网络一直训练但是感觉参数没有变得真正原因，不是reward太发散了，而是梯度并没有共享，真是煞笔，不过750ti训练真是慢。
~巩固了一点点有关gan的知识，觉得gan还是挺好玩的。
下周：
~虽然换了个更高级的显卡，但感觉这样下去还是没办法快速收敛，所以我是想先加个discriminator做成gan的样子，然后用一些低级的算法产生一些数据，然后再去找专家棋局的database，训练到一定程度再继续用a3c。
~参照ikostrikov的方法“实现”梯度共享之后，出现了一个莫名其妙的bug，完成几个回合后，训练就直接停止了，但是没有报错。开debug模式看就提示什么thread not found什么的，我觉得重写一遍找找那里出错了吧。没有保存历史版本的文件真的很伤。
~不是很懂pytorch保存网络参数的机制。如果用A3C算法每个Actor的网络都要完全复制整个网络的参数的话，可能会将权值和梯度都复制一遍，这样就消耗了两倍的显存空间，但是事实上forward可以直接使用shared_module的网络进行计算，然后将产生的梯度单独保存即可，这样就可以节约一点显存了。不过这样做有一个问题，就是shared_module可能会在Actor的一个episode之间变化，可能会对梯度的精度产生一定影响。

**Comment by shawnzzx** [comment]
你对GAN了解得多吗？对GAN很熟悉的话这边有项目，感兴趣的话可以参加一下发文章
